### ISSUE TITLE
Documentation for merging a directory needs to specify that the require has to include the directory

### ISSUE THREAD

**Issue by carimura** [iron-io/docs#107] opened 2012-06-02 00:32 UTC

**Comment by paddycarver** [comment] 2012-06-12 00:35
@carimura Which language? Which documentation?

**Comment by carimura** [comment] 2012-06-12 01:09
Hmm I think I meant here: http://dev.iron.io/worker/reference/worker-files/

One hangup I ran into was not knowing to include the directory when I required the file. For example, this line in the .worker file:

```
dir '../app/models'
```

Caused me to have to require a specific file in the worker like this:

```
require 'models/user'
```

But remembering to include the "models/" in the require took a few frustrating minutes.

**Comment by paddycarver** [comment] 2012-06-12 01:13
Got it, thanks. This may be a "bug" in NG-I'll have to ask @iced what he thinks. We ran into a similar problem in April with the Python library, which has since been patched. Customers were expecting the merged folder to _be_ the root, not be _in_ the root. Either the docs need to specify this or the lib needs to evolve and change behaviour, or both.

**Comment by carimura** [comment] 2012-06-12 01:16
My thought is that the lib is currently acting the _correct_ way ... it's the missing piece of documentation that hung me up for 10 minutes or so.

**Comment by paddycarver** [comment] 2012-06-12 01:28
I'm probably going to have the Python library follow NG's lead, as that's how it was designed in the first place. I just want to make sure I understand _why_ that's the right way.

Should this be in the .worker file docs, though? My understanding is that those simply use the NG merge functions, so wouldn't it belong in the merge docs? We should find some way to call that out in the .worker docs, too, probably.

**Closed as completed** 2012-08-15 23:37 UTC
Labels: needs more info
